export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description: "Get interview questions and model answers based on your role, experience, and specific focus areas no generic responses."
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description: "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations."
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description: "Add personal notes to any question and pin important ones to the top  making your learning more organized and effective."
  },
  {
    id: "04",
    title: "Understand the \"Why\" Behind Answers",
    description: "Beyond just answers  unlock detailed concept explanations generated by AI, helping you truly master each topic."
  },
  {
    id: "05",
    title: "Practice with Confidence",
    description: "Engage in mock interviews with AI feedback on your delivery, content, and areas for improvement, honing your interview skills."
  }
];
